// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oighwkaiqvuoiaopsowy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pZ2h3a2FpcXZ1b2lhb3Bzb3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODUzNzQsImV4cCI6MjA2MTA2MTM3NH0.JOfsN15lg6i7-eqKMjbmTLyEMF6BzywxeofLBT8e2vY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);